# ~/.config/starship.toml 

# Global options (from `settings` block)


add_newline = true
command_timeout = 2000

# This is where the 'format' string goes, translated from `lib.concatStrings`
# Each item in the `lib.concatStrings` list becomes a segment in the string.
format = """\
[ ◢](fg:#84aad9)\
$os\
[](fg:#84aad9 bg:#5bc7b9)\
$directory\
[](fg:#5bc7b9 bg:#4ba6b8)\
$git_branch\
$git_status\
[](fg:#4ba6b8 bg:#769ff0)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:#769ff0)\
$line_break\
$character\
"""

right_format = """\
[](fg:#c48df2)\
$time\
[◤](fg:#c48df2)\ 
"""

# Module Definitions (from nested blocks like `os = { ... }`)

[os]
disabled = false
style = "bg:#84aad9 fg:#101010"

[os.symbols]
NixOS = ""
Fedora = " "
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"

[username]
show_always = true
style_user = "bg:#84aad9 fg:#101010"
style_root = "bg:#5e81ac fg:#101010"
format = "[ $user ]($style)"

[directory]
style = "bg:#5bc7b9 fg:#101010"
format = "[ $path ]($style)"
use_os_path_sep = true
truncate_to_repo = false

[directory.substitutions]
Documents = "󰈙"
Downloads = ""
Music = "󰝚"
Pictures = ""

[git_branch]
symbol = " "
style = "bg:#a3aed2"
format = "[ ( $symbol$branch(:$remote_branch) )](fg:#0f0f0f bg:#4ba6b8)"


[git_status]
style = "bg:#a3aed2"
format = "[ ( $all_status$ahead_behind )](fg:#0f0f0f bg:#4ba6b8)"

[nodejs]
symbol = ""
style = "bg:#a3be8c"
format = "[ $symbol ($version) ](fg:#101010 bg:#769ff0)"

[c]
symbol = ""
style = "bg:#a3be8c"
format = "[ $symbol ($version) ](fg:#101010 bg:#769ff0)"

[cpp]
disabled = false
symbol = ""
style = "bg:#72d0ed"
format = "[ $symbol ($version) ](fg:#101010 bg:#769ff0)"

[rust]
symbol = ""
style = "bg:#72d0ed"
format = "[ $symbol ($version) ](fg:#101010 bg:#769ff0)"

[php]
symbol = ""
style = "bg:#72d0ed"
format = "[ $symbol ($version) ](fg:#101010 bg:#769ff0)"

[java]
symbol = ""
style = "bg:#72d0ed"
format = "[ $symbol ($version) ](fg:#101010 bg:#769ff0)"

[kotlin]
symbol = ""
style = "bg:#72d0ed"
format = "[ $symbol ($version) ](fg:#101010 bg:#769ff0)"

[haskell]
symbol = ""
style = "bg:#72d0ed"
format = "[ $symbol ($version) ](fg:#101010 bg:#769ff0)"

[golang]
symbol = "  "
style = "bg:#69ccdb"
format = "[ $symbol ($version) ](fg:#101010 bg:#769ff0)"

[python]
symbol = ""
style = "bg:#69ccdb"
format = "[ $symbol ($version) ](fg:#101010 bg:#769ff0)"

[docker_context]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $context) ](fg:crust bg:#769ff0)]($style)'

[conda]
symbol = "  "
style = "fg:crust bg:sapphire"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%r"
style = "bg:4b45cc"
format = "[[  $time ](fg:#101010 bg:#c48df2)]($style)"

[line_break]
disabled = false

[character]
disabled = false
success_symbol = "[>](bold fg:#18D661)"
error_symbol = "[>](bold fg:#d62929)"

